# Read the documentation: https://github.com/FriendsOfSymfony/FOSElasticaBundle/blob/master/doc/setup.md
fos_elastica:
    clients:
        default: { url: '%env(ELASTICSEARCH_URL)%' }
    indexes:
        app:
            types:
                user:
                    properties:
                        id: ~
                        ProductCode: ~
                        ProductName: ~
                        ProductDescription: ~
                        Stock: ~
                        CostGBP: ~
                        Discontinued: ~
                    persistence:
                        # the driver can be orm, mongodb or phpcr
                        driver: orm
                        model: App\Entity\Products
                        provider: ~
                        finder: ~